### ISSUE TITLE
Plugin options to be more efficient?

### ISSUE THREAD

**Issue by pyg77** [kanboard/plugin-registration#1]
This plugin is (IMHO) a must-have :)

The workflow is :

> 1.     From the login page a link to the sign up form is displayed
> 2.     The user fill the form and submit
> 3.     The user account is created but it's disabled
> 4.     **The user has to validate his email address to enable the account**

Something seems strange to me, it's that with this workflow anybody could register AND create private projects on the kanboard instance.

So, it would be great if this plugin had these options (cumulative) : 
- "Admin receive email notification when someone register"
- "User receive an email to enable his account"
- "Admin receive email notification when an account has been activated"

This way : 
- the admin could assign the newcomers to projects
- admin could choose if anybody could register (limit by domain name is great, but not really efficient in many contexts)
- admin could _know_ if there are one or many registration pending

**Comment by aslmx** [comment]
Yes, +1!

Please add the option to review self-registrations.

It is really great that the Admin must not enter the user manually, but the user can add himself. 

However in large organisations (with many people using emails with "@domain.tld" it is not sufficient and there must be - an optional -  possibility for admin supervision.

**Comment by bugwatcher** [comment]
This issue has been closed automatically for inactivity after more than 1 year. Unfortunately, this project doesn't have enough resources to manage all these requests. [Read the FAQ](https://docs.kanboard.org/en/1.2.5/developer_guide/faq.html#why-do-you-close-inactive-issues-automatically).
