### ISSUE TITLE
Plugin option to customize email message?

### ISSUE THREAD

**Issue by pyg77** [kanboard/plugin-registration#2]
The mail received by user when auto-registration is not very verbose :)

It would be great if admin could customize this message not just by manipulating t() function in a .php file

**Comment by bugwatcher** [comment]
This issue has been closed automatically for inactivity after more than 1 year. Unfortunately, this project doesn't have enough resources to manage all these requests. [Read the FAQ](https://docs.kanboard.org/en/1.2.5/developer_guide/faq.html#why-do-you-close-inactive-issues-automatically).
