### ISSUE TITLE
Plugin option to resend the email ?

### ISSUE THREAD

**Issue by jadjay** [kanboard/plugin-registration#5]
Sometime for different reasons, the email can't be sent.

If you had fix the mail problem, how can you re-send the very mail ?

**Comment by bugwatcher** [comment]
This issue has been closed automatically for inactivity after more than 1 year. Unfortunately, this project doesn't have enough resources to manage all these requests. [Read the FAQ](https://docs.kanboard.org/en/1.2.5/developer_guide/faq.html#why-do-you-close-inactive-issues-automatically).
