### ISSUE TITLE
Able to chose the possibility of email confirmaion

### ISSUE THREAD

**Issue by DoumeDuSud** [kanboard/plugin-registration#6]
Is it possible to create (or to indicate witch parameter to change in the config file) a check box to remove the necessity of confirmation by email.

Thanks for all

**Comment by bugwatcher** [comment]
This issue has been closed automatically for inactivity after more than 1 year. Unfortunately, this project doesn't have enough resources to manage all these requests. [Read the FAQ](https://docs.kanboard.org/en/1.2.5/developer_guide/faq.html#why-do-you-close-inactive-issues-automatically).
